# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.FileField(null=True, upload_to='blog_uploads/%Y/%m/%d/'),
        ),
    ]
