# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20171228_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(upload_to='blog_uploads/%Y/%m/%d/'),
        ),
    ]
