# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-12 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.FileField(upload_to='blog_uploads/%Y/%m/%d/'),
        ),
    ]
