# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-19 11:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20180117_1059'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Search',
        ),
    ]
