# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-12 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=70, null=True, unique=True)),
                ('message', models.TextField()),
                ('sent_on', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
