# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='portfolio/%y/%m/%d/')),
            ],
        ),
    ]
