# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-29 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio_list',
            name='name',
        ),
        migrations.AddField(
            model_name='portfolio_list',
            name='card_title',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
